### ISSUE TITLE
未从沙箱输出中捕获到合法的输出

### ISSUE THREAD

**Issue by Yumega** [AstrBotDevs/AstrBot#646]
[08:43:46] [WARNING] [main.py:395]: 未从沙箱输出中捕获到合法的输出。沙箱输出日志: ["python: can't open file '/astrbot_sandbox/exec.py': [Errno 2] No such file or directory\n"]

**Comment by Soulter** [comment]
可以提供下 AstrBot 的部署方式、操作系统类型吗？

**Comment by Yumega** [comment]
> 可以提供下 AstrBot 的部署方式、操作系统类型吗？

设备型号：x86 Generic
系统：openWRT
docker 部署

```
services:
  astrbot:
    image: soulter/astrbot:latest
    container_name: astrbot
    network_mode: bridge
    restart: always
    ports: 
      - "6200:6200"  # 作为反向websocket端口
      - "6185:6185"  # web-ui
      - "11451:11451"
    volumes:
      - /mnt/sdb1/docker/opt/AstrBot/data:/AstrBot/data
      - /var/run/docker.sock:/var/run/docker.sock
```
